# Generated by Django 5.0.8 on 2024-08-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_course_created_at_course_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='eee', max_length=100),
        ),
    ]
