# Generated by Django 5.0.8 on 2024-08-29 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_crnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crnotification',
            name='creator',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'cr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='crnotification',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'cr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cr_notifications_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
