# Generated by Django 5.0.8 on 2024-08-30 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='cr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_attendance', to=settings.AUTH_USER_MODEL),
        ),
    ]
